ENABLE:
  - MARKDOWN
  - SPELL
  - YAML
DISABLE_LINTERS:
  - SPELL_CSPELL
PRINT_ALPACA: false
FLAVOR_SUGGESTIONS: false
SHOW_SKIPPED_LINTERS: false
ADDITIONAL_EXCLUDED_DIRECTORIES: [external, lwip/lwip-*]
